export const technologies = [
  {
    id: 1,

    category: "lib",
    name: "ReactJs",
    png: "https://cdn4.iconfinder.com/data/icons/logos-3/600/React.js_logo-512.png",
    description: "libreria para JavaScript",
    exp: "+6 meses",
  },
  {
    id: 2,
    category: "len",
    name: "JavaScript",
    png: "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    description: "Lenguaje de programación",
    exp: "+1 año",
  },
  {
    id: 3,
    category: "framework",
    name: "Laravel",
    png: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Laravel.svg/985px-Laravel.svg.png",
    description: "Framework para backend con PHP",
    exp: "+1 año",
  },
  {
    id: 4,
    category: "len",
    name: "PHP",
    png: "https://cdn.freebiesupply.com/logos/large/2x/php-logo-png-transparent.png",
    description: "Lenguaje de programación",
    exp: "+2 años",
  },
  {
    id: 5,
    category: "maq",
    name: "HTML5",
    png: "https://cdn-icons-png.flaticon.com/512/732/732212.png",
    description: "lenguaje de maquetado",
    exp: "+2 años",
  },
  {
    id: 6,
    category: "style",
    name: "CSS3",
    png: "https://danielcastillo.dev/assets/img/skills/css.png",
    description: "Cascade Style Sheet",
    exp: "+1 año",
  },
  {
    id: 7,
    category: "db",
    name: "MySQL",
    png: "https://pngimg.com/uploads/mysql/mysql_PNG35.png",
    description: "Base de datos relacional",
    exp: "+2 años",
  },
];
